package slimeattack07.threedee.init;

import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import slimeattack07.threedee.Threedee;
import slimeattack07.threedee.objects.blocks.CustomBlockBaseRotatable;
import slimeattack07.threedee.util.helpers.ModShapes;

public class CommonModelBlocks {
	public static final DeferredRegister<Block> COMMON = DeferredRegister.create(ForgeRegistries.BLOCKS, Threedee.MOD_ID);
	
	public static final RegistryObject<Block> APPLE = COMMON.register("apple", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> APPLE_1 = COMMON.register("apple_1", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> BACKPACK = COMMON.register("backpack", () -> new CustomBlockBaseRotatable(ModShapes.W12_H12, 1));
	public static final RegistryObject<Block> BAG_FISH = COMMON.register("bag_fish", () -> new CustomBlockBaseRotatable(ModShapes.W12_H8, 1));
	public static final RegistryObject<Block> BAG_FLOUR = COMMON.register("bag_flour", () -> new CustomBlockBaseRotatable(ModShapes.W12_H8, 1));
	public static final RegistryObject<Block> BAG_FLOWER = COMMON.register("bag_flower", () -> new CustomBlockBaseRotatable(ModShapes.W12_H8, 1));
	public static final RegistryObject<Block> BAG_SUGAR = COMMON.register("bag_sugar", () -> new CustomBlockBaseRotatable(ModShapes.W12_H8, 1));
	public static final RegistryObject<Block> BARREL = COMMON.register("barrel", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> BASKETBALL = COMMON.register("basketball", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> BEACHBALL = COMMON.register("beachball", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> BLUEBERRIES = COMMON.register("blueberries", () -> new CustomBlockBaseRotatable(ModShapes.W16_H1, 1));
	public static final RegistryObject<Block> BONEMEAL = COMMON.register("bonemeal", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> BOX_CLOSED = COMMON.register("box_closed", () -> new CustomBlockBaseRotatable(ModShapes.W12_H12, 1));
	public static final RegistryObject<Block> BOX_DOCUMENTS = COMMON.register("box_documents", () -> new CustomBlockBaseRotatable(ModShapes.W12_H16, 1));
	public static final RegistryObject<Block> BOX_OPEN = COMMON.register("box_open", () -> new CustomBlockBaseRotatable(ModShapes.W12_H16, 1));
	public static final RegistryObject<Block> BREAD = COMMON.register("bread", () -> new CustomBlockBaseRotatable(ModShapes.W16_H8, 1));
	public static final RegistryObject<Block> BURGER = COMMON.register("burger", () -> new CustomBlockBaseRotatable(ModShapes.W12_H12, 1));
	public static final RegistryObject<Block> CABBAGE = COMMON.register("cabbage", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> CANDLE = COMMON.register("candle", () -> new CustomBlockBaseRotatable(ModShapes.W6_H10, 1));
	public static final RegistryObject<Block> CANNONBALL = COMMON.register("cannonball", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAN_OF_SOUP = COMMON.register("can_of_soup", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_BLACK = COMMON.register("car_black", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_BLUE = COMMON.register("car_blue", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_BROWN = COMMON.register("car_brown", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_CYAN = COMMON.register("car_cyan", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_GRAY = COMMON.register("car_gray", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_GREEN = COMMON.register("car_green", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_LIGHT_BLUE = COMMON.register("car_light_blue", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_LIGHT_GRAY = COMMON.register("car_light_gray", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_LIME = COMMON.register("car_lime", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_MAGENTA = COMMON.register("car_magenta", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_ORANGE = COMMON.register("car_orange", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_PINK = COMMON.register("car_pink", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_PURPLE = COMMON.register("car_purple", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_RED = COMMON.register("car_red", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_WHITE = COMMON.register("car_white", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CAR_YELLOW = COMMON.register("car_yellow", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> CHEESE = COMMON.register("cheese", () -> new CustomBlockBaseRotatable(ModShapes.W16_H6, 1));
	public static final RegistryObject<Block> CHUNK_BRONZE = COMMON.register("chunk_bronze", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> CHUNK_COPPER = COMMON.register("chunk_copper", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> CHUNK_PEWTER = COMMON.register("chunk_pewter", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> CHUNK_TIN = COMMON.register("chunk_tin", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> CITY_BUILDING = COMMON.register("city_building", () -> new CustomBlockBaseRotatable(ModShapes.W16_H20, 1));
	public static final RegistryObject<Block> CLAY_BALL = COMMON.register("clay_ball", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> CLOWNFISH = COMMON.register("clownfish", () -> new CustomBlockBaseRotatable(ModShapes.W8_H4, 1));
	public static final RegistryObject<Block> COCONUT = COMMON.register("coconut", () -> new CustomBlockBaseRotatable(ModShapes.W8_H4, 1));
	public static final RegistryObject<Block> COD = COMMON.register("cod", () -> new CustomBlockBaseRotatable(ModShapes.W8_H4, 1));
	public static final RegistryObject<Block> CORN = COMMON.register("corn", () -> new CustomBlockBaseRotatable(ModShapes.W8_H16, 1));
	public static final RegistryObject<Block> COTTON = COMMON.register("cotton", () -> new CustomBlockBaseRotatable(ModShapes.W8_H16, 1));
	public static final RegistryObject<Block> CRANBERRIES = COMMON.register("cranberries", () -> new CustomBlockBaseRotatable(ModShapes.W16_H1, 1));
	public static final RegistryObject<Block> EGG = COMMON.register("egg", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> FERMENTED_SPIDEREYE = COMMON.register("fermented_spidereye", () -> new CustomBlockBaseRotatable(ModShapes.W6_H6, 1));
	public static final RegistryObject<Block> FROG = COMMON.register("frog", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> GARDEN_GNOME = COMMON.register("garden_gnome", () -> new CustomBlockBaseRotatable(ModShapes.W12_H16, 1));
	public static final RegistryObject<Block> GOLDEN_CANDLE = COMMON.register("golden_candle", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> GRAPEFRUIT = COMMON.register("grapefruit", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> HAYBALE = COMMON.register("haybale", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> HEDGEHOG = COMMON.register("hedgehog", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> JAM_APRICOT = COMMON.register("jam_apricot", () -> new CustomBlockBaseRotatable(true, ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> JAM_BLUEBERRY = COMMON.register("jam_blueberry", () -> new CustomBlockBaseRotatable(true, ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> JAM_LEMON_CURD = COMMON.register("jam_lemon_curd", () -> new CustomBlockBaseRotatable(true, ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> JAM_STRAWBERRY = COMMON.register("jam_strawberry", () -> new CustomBlockBaseRotatable(true, ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> JELLYFISH = COMMON.register("jellyfish", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> LEMON = COMMON.register("lemon", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> LOG_PILE = COMMON.register("log_pile", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> MUFFIN = COMMON.register("muffin", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> MUSTARD = COMMON.register("mustard", () -> new CustomBlockBaseRotatable(true, ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> NEWSPAPERS = COMMON.register("newspapers", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> PARROT = COMMON.register("parrot", () -> new CustomBlockBaseRotatable(ModShapes.W12_H16, 1));
	public static final RegistryObject<Block> PEAR = COMMON.register("pear", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PENCIL_SHARPNER_BLUE = COMMON.register("pencil_sharpner_blue", () -> new CustomBlockBaseRotatable(ModShapes.W8_H3, 1));
	public static final RegistryObject<Block> PENCIL_SHARPNER_GREEN = COMMON.register("pencil_sharpner_green", () -> new CustomBlockBaseRotatable(ModShapes.W8_H3, 1));
	public static final RegistryObject<Block> PENCIL_SHARPNER_RED = COMMON.register("pencil_sharpner_red", () -> new CustomBlockBaseRotatable(ModShapes.W8_H3, 1));
	public static final RegistryObject<Block> PENCIL_SHARPNER_YELLOW = COMMON.register("pencil_sharpner_yellow", () -> new CustomBlockBaseRotatable(ModShapes.W8_H3, 1));
	public static final RegistryObject<Block> PLUM = COMMON.register("plum", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> POPCORN = COMMON.register("popcorn", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_BLACK = COMMON.register("present_black", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_BLUE = COMMON.register("present_blue", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_BROWN = COMMON.register("present_brown", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_CYAN = COMMON.register("present_cyan", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> PRESENT_GRAY = COMMON.register("present_gray", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> PRESENT_GREEN = COMMON.register("present_green", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_LIGHT_BLUE = COMMON.register("present_light_blue", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> PRESENT_LIGHT_GRAY = COMMON.register("present_light_gray", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_LIME = COMMON.register("present_lime", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_MAGENTA = COMMON.register("present_magenta", () -> new CustomBlockBaseRotatable(ModShapes.W16_H8, 1));
	public static final RegistryObject<Block> PRESENT_ORANGE = COMMON.register("present_orange", () -> new CustomBlockBaseRotatable(ModShapes.W8_H16, 1));
	public static final RegistryObject<Block> PRESENT_PINK = COMMON.register("present_pink", () -> new CustomBlockBaseRotatable(ModShapes.W12_H8, 1));
	public static final RegistryObject<Block> PRESENT_PURPLE = COMMON.register("present_purple", () -> new CustomBlockBaseRotatable(ModShapes.W8_H16, 1));
	public static final RegistryObject<Block> PRESENT_RED = COMMON.register("present_red", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> PRESENT_WHITE = COMMON.register("present_white", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> PRESENT_YELLOW = COMMON.register("present_yellow", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> RADISH = COMMON.register("radish", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> RASPBERRIES = COMMON.register("raspberries", () -> new CustomBlockBaseRotatable(ModShapes.W16_H1, 1));
	public static final RegistryObject<Block> SALMON = COMMON.register("salmon", () -> new CustomBlockBaseRotatable(ModShapes.W8_H4, 1));
	public static final RegistryObject<Block> SANDWHICH = COMMON.register("sandwhich", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> SNOW_BALL = COMMON.register("snow_ball", () -> new CustomBlockBaseRotatable(ModShapes.W8_H6, 1));
	public static final RegistryObject<Block> SOCCERBALL = COMMON.register("soccerball", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> STONE_CREEPER = COMMON.register("stone_creeper", () -> new CustomBlockBaseRotatable(ModShapes.W12_H26, 1));
	public static final RegistryObject<Block> SUPPLY_BUNDLE = COMMON.register("supply_bundle", () -> new CustomBlockBaseRotatable(ModShapes.W12_H8, 1));
	public static final RegistryObject<Block> TABLE_ACACIA = COMMON.register("table_acacia", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TABLE_BIRCH = COMMON.register("table_birch", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TABLE_CRIMSON = COMMON.register("table_crimson", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TABLE_DARK_OAK = COMMON.register("table_dark_oak", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TABLE_JUNGLE = COMMON.register("table_jungle", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TABLE_OAK = COMMON.register("table_oak", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TABLE_SPRUCE = COMMON.register("table_spruce", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TABLE_WARPED = COMMON.register("table_warped", () -> new CustomBlockBaseRotatable(ModShapes.W16_H16, 1));
	public static final RegistryObject<Block> TEDDY_BEAR = COMMON.register("teddy_bear", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> TOILET_PAPER = COMMON.register("toilet_paper", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> TOMATO = COMMON.register("tomato", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> VOLLEYBALL = COMMON.register("volleyball", () -> new CustomBlockBaseRotatable(ModShapes.W8_H8, 1));
	public static final RegistryObject<Block> WOOD_ACACIA = COMMON.register("wood_acacia", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> WOOD_BIRCH = COMMON.register("wood_birch", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> WOOD_CRIMSON = COMMON.register("wood_crimson", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> WOOD_DARK_OAK = COMMON.register("wood_dark_oak", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> WOOD_JUNGLE = COMMON.register("wood_jungle", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> WOOD_OAK = COMMON.register("wood_oak", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> WOOD_SPRUCE = COMMON.register("wood_spruce", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
	public static final RegistryObject<Block> WOOD_WARPED = COMMON.register("wood_warped", () -> new CustomBlockBaseRotatable(ModShapes.W16_H4, 1));
}
